// <auto-generated>
//     This code was generated by NSwag.
// </auto-generated>

using System.Net.Http.Json;
using FlowStream.Connect.Shared.DTOs;

namespace FlowStream.Connect.Portal.ApiClient;

public partial class ConnectApiClient(HttpClient httpClient)
{
    public async Task<SubmitDocumentResponse?> SubmitDocumentAsync(SubmitDocumentRequest request, CancellationToken cancellationToken = default)
    {
        var response = await httpClient.PostAsJsonAsync("api/connect/documents", request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadFromJsonAsync<SubmitDocumentResponse>(cancellationToken: cancellationToken);
    }

    public async Task<DocumentStatusResponse?> GetDocumentStatusAsync(string documentId, CancellationToken cancellationToken = default)
    {
        return await httpClient.GetFromJsonAsync<DocumentStatusResponse>($"api/connect/documents/{documentId}", cancellationToken);
    }
}
